#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="silvervpn"
APP_NAME="SilverVPN"
BIN_DIR="$HOME/.local/bin"
APP_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/icons/hicolor/256x256/apps"
WRAPPER="$BIN_DIR/$APP_ID"
DESKTOP_FILE="$APP_DIR/$APP_ID.desktop"
ICON_FILE="$ICON_DIR/$APP_ID.png"
DESKTOP_DIR=""
SHELL_HOOK_FILE="$HOME/.config/SilverVPN/shell-hook.sh"

if command -v xdg-user-dir >/dev/null 2>&1; then
  DESKTOP_DIR="$(xdg-user-dir DESKTOP 2>/dev/null || true)"
fi
if [[ -z "$DESKTOP_DIR" ]]; then
  DESKTOP_DIR="$HOME/Desktop"
fi

cd "$ROOT_DIR"

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required. Install Node.js 18+ first." >&2
  exit 1
fi
if ! command -v npm >/dev/null 2>&1; then
  echo "npm is required. Install npm first." >&2
  exit 1
fi

echo "Installing npm dependencies"
npm install

echo "Installing mihomo core"
"$ROOT_DIR/scripts/install-core.sh"
chmod 0755 "$ROOT_DIR/scripts/core-watchdog.sh" "$ROOT_DIR/scripts/install-tun.sh"

mkdir -p "$BIN_DIR" "$APP_DIR" "$ICON_DIR"
mkdir -p "$(dirname "$SHELL_HOOK_FILE")"

ELECTRON_BINARY="$ROOT_DIR/node_modules/electron/dist/electron"
if [[ ! -x "$ELECTRON_BINARY" ]]; then
  echo "Electron runtime was not installed correctly: $ELECTRON_BINARY" >&2
  exit 1
fi

if [[ ! -f "$ROOT_DIR/renderer/static/media/silvervpn.png" && -f "$ROOT_DIR/renderer/static/media/silvervpn.png.base64" ]]; then
  base64 --decode "$ROOT_DIR/renderer/static/media/silvervpn.png.base64" > "$ROOT_DIR/renderer/static/media/silvervpn.png"
fi

cat > "$WRAPPER" <<EOF
#!/bin/bash
set -euo pipefail
APP_DIR="$ROOT_DIR"
ELECTRON="\$APP_DIR/node_modules/electron/dist/electron"
STATE_DIR="\${XDG_STATE_HOME:-\$HOME/.local/state}/SilverVPN"
LOG_FILE="\$STATE_DIR/launcher.log"
mkdir -p "\$STATE_DIR"
exec >>"\$LOG_FILE" 2>&1
printf '\\n[%s] Starting SilverVPN\\n' "\$(date --iso-8601=seconds 2>/dev/null || date)"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\${PATH:-}"
cd "\$APP_DIR"
if [[ ! -x "\$ELECTRON" ]]; then
  echo "Electron runtime is missing: \$ELECTRON"
  exit 1
fi
exec "\$ELECTRON" --no-sandbox "\$APP_DIR"
EOF
chmod +x "$WRAPPER"

rm -f "$BIN_DIR/silvervpn-run" "$BIN_DIR/silvervpn-code" "$BIN_DIR/silvervpn-claude"

cat > "$SHELL_HOOK_FILE" <<'EOF'
# Generated by SilverVPN. This file is safe to source from Bash and Zsh.
silvervpn_sync_proxy_env() {
  local state_file="$HOME/.config/SilverVPN/shell-proxy.sh"
  if [[ -r "$state_file" ]]; then
    # shellcheck disable=SC1090
    source "$state_file"
  fi
}

if [[ -n "${BASH_VERSION:-}" ]]; then
  case ";${PROMPT_COMMAND:-};" in
    *";silvervpn_sync_proxy_env;"*) ;;
    *) PROMPT_COMMAND="silvervpn_sync_proxy_env${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
  esac
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  autoload -Uz add-zsh-hook 2>/dev/null || true
  if type add-zsh-hook >/dev/null 2>&1; then
    add-zsh-hook precmd silvervpn_sync_proxy_env
  fi
fi

silvervpn_sync_proxy_env
EOF
chmod 0600 "$SHELL_HOOK_FILE"

install_shell_hook() {
  local shell_rc="$1"
  local source_line='[[ -r "$HOME/.config/SilverVPN/shell-hook.sh" ]] && source "$HOME/.config/SilverVPN/shell-hook.sh"'
  touch "$shell_rc"
  if ! grep -Fq '.config/SilverVPN/shell-hook.sh' "$shell_rc"; then
    {
      printf '\n# SilverVPN terminal proxy integration\n'
      printf '%s\n' "$source_line"
    } >> "$shell_rc"
  fi
}

install_shell_hook "$HOME/.bashrc"
if [[ -f "$HOME/.zshrc" ]] || [[ "${SHELL:-}" == */zsh ]]; then
  install_shell_hook "$HOME/.zshrc"
fi

if [[ -f "$ROOT_DIR/renderer/static/media/silvervpn.png" ]]; then
  cp "$ROOT_DIR/renderer/static/media/silvervpn.png" "$ICON_FILE"
elif [[ -f "$ROOT_DIR/renderer/static/media/ava.e147bdeb.png" ]]; then
  cp "$ROOT_DIR/renderer/static/media/ava.e147bdeb.png" "$ICON_FILE"
fi

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=$APP_NAME
Comment=SilverVPN Linux proxy client
Exec=$WRAPPER
TryExec=$WRAPPER
Path=$ROOT_DIR
Icon=$ICON_FILE
Terminal=false
Categories=Network;
StartupNotify=true
StartupWMClass=SilverVPN
X-GNOME-UsesNotifications=true
EOF
chmod 0644 "$DESKTOP_FILE"

rm -f "$APP_DIR/xiongmao-vpn-linux.desktop" "$APP_DIR/silvervpn-code.desktop"

if [[ -n "$DESKTOP_DIR" && "$DESKTOP_DIR" == "$HOME"* ]]; then
  mkdir -p "$DESKTOP_DIR"
  cp "$DESKTOP_FILE" "$DESKTOP_DIR/$APP_NAME.desktop"
  chmod 0755 "$DESKTOP_DIR/$APP_NAME.desktop"
  if command -v gio >/dev/null 2>&1; then
    gio set "$DESKTOP_DIR/$APP_NAME.desktop" metadata::trusted true 2>/dev/null || true
  fi
  rm -f "$DESKTOP_DIR/熊猫上网 Linux.desktop"
fi

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$APP_DIR" 2>/dev/null || true
fi

echo "Installed $APP_NAME"
echo "Launch from the application menu or run: $WRAPPER"
echo "Desktop launcher log: ${XDG_STATE_HOME:-$HOME/.local/state}/SilverVPN/launcher.log"
echo "Optional TUN support (one-time privileged install): $ROOT_DIR/scripts/install-tun.sh"
